### PR TITLE
getName() typo

### LINKED ISSUE #19: JavaModule#getName() typo: geName()
`JavaModule#geName()` is a typo; should be `getName()`

### PR DESCRIPTION
**Pull request by rgoldberg**
Fixes #19: typo in `JavaModule#geName()`; now `getName()`.

I included my build script updates in this PR, as subsequent sequential PRs are all based on this, and I wanted to have a clean build with which to work.

Also, please don't merge in the two pending PRs from other people as my fork supports those features along with many more features, and having to rebase would be a huge pain.

### CODE REVIEW

**Comment by rgoldberg** [comment]
@oehme 

Can someone look into this?

I will create serial PRs for all my other commits that resolve other issues in this plugin, each one after the previous PR is merged.

If you look at the issues, you can see I've fixed a good deal of them…

BTW, sorry about the multiple commits referenced in some of the issues; I pushed the same commits multiple times after having reworded commits messages and/or rebasing. I didn't know that the obsolete dangling commits would still be linked from the issues they reference. I'm trying to somehow prune them…

Thanks for all the help.

**Comment by lion7** [comment]
+1
I would like to see this merged, currently I have to explicitly invoke the get method from my Kotlin build script because it doesn't match the 'call getters as property' convention.

**Comment by rgoldberg** [comment]
@lion7 I've made a lot of fixes for many issues with this plugin.  If they don't accept them, you can use my version of the plugin from https://plugins.gradle.org/plugin/rgoldberg.experimental-jigsaw.

Note that if I must maintain my own version of the plugin, this isn't the longterm plugin name.  I'll have my domain name sorted out in a month or so, at which time I'll change the plugin name.

My version reads the module name from the `module-info.java`, so the `javaModule` extension is no longer provided by the plugin.

My version fixes other issues, too.  You can see which ones by looking at the issues of this original version of the plugin, and looking for commits for those issues.

If you run into any problems using my plugin, feel free to add an issue on [my clone](https://github.com/rgoldberg/gradle-java-modules).  Some situations aren't yet covered by my version, but I think that anything that works with the original plugin should also work with my version.

**Comment by oehme** [comment]
Sorry for the late replies. I'm afraid almost no one is following this repo, as it was meant mostly as a sample. But changes that make sense for everyone are of course welcome. The Gradle team is currently very busy preparing for 5.0, so I suggest you use the forked version of the plugin until we have some time to review these PRs.

Alternatively we could also point our documentation to your fork and thus give you full freedom to go ahead without waiting for our review.

**Comment by rgoldberg** [comment]
@oehme No problem about the timing of your reply.  

I will sort out a domain name for myself soon; once I've properly renamed my fork's plugin name, I'll let you know about it for broader publication (I don't want to change the name of my plugin on people).

Should I leave the packages in the plugin as `org.gradle.java*`, in anticipation of future PR acceptance, or should I move the code into packages under my future domain?  I don't want to trample on your package space, but I don't want to unnecessarily complicate future PRs, or to unnecessarily have a package renaming branch…

Good luck with 5.0.  Is there any info about new features, anticipated release date, etc.?

Thanks again for your help answering my questions in the Gradle forum.

**Comment by oehme** [comment]
You can get info on 5.0 by looking at the 5.0 RC1 GitHub milestone.

I think if you are going to have a longer-lived fork then renaming everything makes sense. If we decide to integrate things back we can always do another rename, shouldn't be much more than some find&replace :)

**Comment by rgoldberg** [comment]
Thanks.  Will do.

**Review by JLLeitschuh — APPROVED** [review]
LGTM! @oehme?

**Comment by rgoldberg** [comment]
@JLLeitschuh: Thanks.

I’m about to rebase a few subsequent commits and push them to my fork, so don’t bother reading anything else from my fork until I let you know when everything has been cleaned up.

I’ve tried to update to use the latest Gradle APIs. What old versions of Gradle must my fork support in order to be useful?

Since my fork uses `register(…)` methods, is 4.10 old enough as the minimum supported Gradle version? If not, I can use Grolifant.

**Comment by rgoldberg** [comment]
Which versions do you prefer as the lowest supported plugin build & application versions?

I can make my fork's binary plugin work with the following Gradle versions (each followed by what prevents using earlier versions):

- 4.10.3+: using `TestFrameworkDetector#processTestClass(RelativeFile)`, which was added as a replacement for `TestFrameworkDetector#processTestClass(File)`, which was removed in 4.10.3. 
 To support 4.10.2 or earlier, I would have to use reflection or Groovy to use the old version of the method.
- 4.10+: CME in 4.9, which I won't diagnose unless you require supporting 4.9 or older.
- 4.9+: using configuration avoidance methods (definitely in build scripts, not sure if in the built binary plugin, so might only limit build Gradle versions instead of runtime Gradle versions).
- some older version of 4.x: via Grolifant `org.ysb33r.grolifant.api.TaskProvider#registerTask` & somehow avoiding using other configuration avoidance methods (again, not sure if build-only or actual runtime issue).

The code only uses the following in build scripts, so they should only limit Gradle versions for building the plugin, not for applying it:

- 5.6+: using `enableFeaturePreview("GROOVY_COMPILATION_AVOIDANCE")`.
- 5.0+: using Kotlin DSL type-safe `TaskContainer` extension methods that return `TaskProvider`, e.g., `tasks.build`.
- ?: using Kotlin DSL.  Not sure about what is the oldest version that the build is compatible with.

The code no longer uses the following methods so they shouldn't affect Gradle version compatibility:

- 5.1+: using `Jar#getArchiveFile()`
- 5.0+: using `TaskContainer#named(String, Class)`

**Pull request closed without merging**
